prgrms-be-devcourse/BE-02-MarBox

- .github/workflows/gradle.yml
> chore : GitHub Actions 설정

- build.gradle
- 로그인 관련 의존성 추가
- SpringSecurity, SpringSecurity Test, Jwt 의존성 추가
- PR을 보내보고 싶어서, 작은 단위로 보내봅니다! 🥲
> [#16] 로그인 관련 의존성 추가

- build.gradle
- lang3 라이브러리 추가
- toStringBuilder 사용하고자 추가
> chore(build.gradle): lang3 라이브러리 추가

- src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateSchedule.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/utils/ScheduleConverter.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceMockTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
- Schedule 네이밍 컨벤션 맞추기
- fix #32 
- ScheduleRecord -> RequestCreateSchedule 변경
- ScheduleConverter 클래스 추가
> [#32] Schedule 네이밍 컨벤션 맞추기

- build.gradle
- src/main/java/prgrms/marco/be02marbox/MarBoxApplication.java
- src/main/java/prgrms/marco/be02marbox/config/JwtConfigure.java
- src/main/java/prgrms/marco/be02marbox/config/WebSecurityConfigure.java
- src/main/java/prgrms/marco/be02marbox/domain/user/User.java
- src/main/java/prgrms/marco/be02marbox/domain/user/controller/UserController.java
- src/main/java/prgrms/marco/be02marbox/domain/user/dto/RequestSignInUser.java
- src/main/java/prgrms/marco/be02marbox/domain/user/dto/ResponseLoginUser.java
- src/main/java/prgrms/marco/be02marbox/domain/user/exception/InvalidEmailException.java
- src/main/java/prgrms/marco/be02marbox/domain/user/exception/Message.java
- src/main/java/prgrms/marco/be02marbox/domain/user/exhandler/ExceptionController.java
- src/main/java/prgrms/marco/be02marbox/domain/user/jwt/Jwt.java
- src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthentication.java
- src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProvider.java
- src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationToken.java
- src/main/java/prgrms/marco/be02marbox/domain/user/service/UserService.java
- src/main/resources/application.yml
- src/test/java/prgrms/marco/be02marbox/config/JwtConfigureTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/controller/UserControllerTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/dto/RequestSignInUserTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProviderTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/service/UserServiceTest.java
- src/test/resources/jwt-config.properties
- 고객 로그인 기능 개발
- 고객이 로그인 할 수 있다.
- commit 바디에 자세히 남겼습니다!
- 로그인에 성공하면 jwt 토큰을 발급 받는다.
- 팀 코딩 컨벤션 적용 못한 부분이 있습니다. (ex) dto, exception)  이 부분은 따로 이슈로 만들어 PR 보내겠습니다! 😄
> [#5] 고객은 로그인 할 수 있다.

- src/main/java/prgrms/marco/be02marbox/domain/theater/Region.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/TheaterRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterServiceTest.java
지역별 영화관 조회 기능 
TheaterService : findTheaterServiceByRegion 메서드 추가
TheaterRepository : findByRegion 메서드 추가 
관리자, 고객 모두 지역별로 영화관을 조회할 수 있다.
> [#58] 관리자, 고객은 지역별로 영화관을 조회할 수 있다.

- .github/workflows/marbox-ci.yml
- docker-compose.yml
- docker 이용하는 github actions workflow 추가
- docker 이용하는 github actions workflow 추가
- 새로운 github actions workflow 추가
- docker-compose 파일 추가
- 개발 환경 DB를 docker을 이용한 mysql을 사용하면, End2End 테스트 작성시 개발 환경과 같은 DB를 보게 작성하는 게 좋습니다. ([참조](https://umbum.dev/1127))
- 테스트시 개발 환경과 같은 DB를 보게하려면 Github Actions를 수행할 때, docker 컨테이너를 만들어주는 작업을 추가해야 합니다.
> [#61] docker 이용하는 github actions workflow 추가

- .github/pull_request_template.md
- PR template 변경 - main 브랜치 반영
- 제목 작성방법 추가
- 리뷰어 지정목록 추가
> [#71] PR template 변경 - main으로 반영

- src/main/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestController.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/service/MovieService.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestControllerTest.java
- Movie 리팩토링
- 상수 값으로 페이징 값 처리
- 라인 변경
- ex) 관리자 권한이 있는 계정만 유저 정보를 조회할 수 있다.
- 기능 변화가 없기 때문에 바로 머지 하겠습니다
> [#73] Movie 리팩토링

- src/main/java/prgrms/marco/be02marbox/domain/movie/service/MovieService.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/service/utils/MovieConverter.java
- MovieService 주석 추가
- MovieConverter 주석 추가
> [#85] MovieService 주석 추가

- src/docs/asciidoc/theater.adoc
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/TheaterRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/controller/TheaterControllerTest.java
Restdocs 추가
List<Theater> findByRegion(Region region) -> List<Theater> findAllByRegion(Region region) 으로 변경
> [#92] Theater Restdocs 추가

- .gitignore
- src/main/java/prgrms/marco/be02marbox/domain/exception/handler/MovieExceptionHandler.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/Movie.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestController.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/dto/RequestCreateMovie.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/dto/ResponseCreateMovie.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/service/MovieService.java
- src/main/java/prgrms/marco/be02marbox/domain/movie/service/utils/MovieConverter.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestControllerTest.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/repository/MovieRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/service/MovieServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceMockTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
- Movie 포스터 등록 기능 추가
- 포스터 이름은 중복이 발생할 가능성이 있기 때문에 [포스터 id + 파일 확장자명]으로 저장이 됩니다
- Movie 포스터 등록 기능 추가 되었습니다
> [#91] Movie 포스터 등록 기능 추가

- src/docs/asciidoc/schedule.adoc
- src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
- src/main/java/prgrms/marco/be02marbox/domain/exception/handler/TheaterExceptionHandler.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleController.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleControllerTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
- 영화관, 날짜 요청 -> 영화 정보 조회 구현
- 영화관 ID, 특정 날짜를 요청하면 영화관과 날짜에 맞는 영화 리스트를 반환
- restdocds
<h3 id="_영화관과_상영_날짜를_요청하여_영화_리스트_가져오기" style="box-sizing: border-box; margin: 1em 0px 0.5em; padding: 0px; font-family: &quot;Open Sans&quot;, &quot;DejaVu Sans&quot;, sans-serif; font-weight: 300; font-style: normal; color: rgb(204, 204, 204); text-rendering: optimizelegibility; line-height: 1.2; font-size: 1.375em; word-spacing: -0.05em; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; -webkit-text-stroke-width: 0px; background-color: rgb(69, 73, 74); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">영화관과 상영 날짜를 요청하여 …
> [#107] 사용자는 한 영화관에서 특정 날짜에 상영하는 영화 정보를 확인한다

- src/main/resources/application-test.yml
- application-test.yml 데이터소스 엔드포인트 수정하기
- test 프로파일에서 RDS 접근 성공
- application-test.yml의 datasource.url 수정
- 어제 AWS 설정하면서, RDS를 새로 만들었습니다. 그래서 설정 파일의 datasource url을 수정했습니다.
> [#114] application-test.yml 데이터소스 엔드포인트 수정하기

- src/main/java/prgrms/marco/be02marbox/config/WebSecurityConfigure.java
- 개발 완료한 API 권한 최신화하기
- 개발 완료한 API 권한 최신화하기
- 스케줄 관련 조회 API 접근 권한 없앰. (한주님 피드백)
- API 권한 관련 추가하고 싶은 부분 있으시면, API URL과 원하는 권한 말씀해 주세요!
> [#119] 개발 완료한 API 권한 최신화하기

- README.md
- REAMD ME 내용 추가 
- get start 내용 추가
- 개발환경 내용 추가
- 이슈번호 % 5
- default: `ksy90101`
- 0: `hyuk0309`, `wisehero`, `sdardew`
- 1: `Pawer0223`, `sdardew`, `hyuk0309`
- 2: `sdardew` ,` Pawer0223`, `yanJuicy`
- 3: `yanJuicy`, `wisehero`, `Pawer0223`
- 4: `wisehero`, `hyuk0309`, `yanJuicy`
> #[144] REAMD ME 내용 추가 

- README.md
> [#155] 브랜치 전략 이미지로 표현

- README.md
- README 코드 컨벤션 작성
- README 코드 컨벤션 작성
- README Commit 컨벤션 작성
- README PR/Issue 컨벤션 작성
- README Merge 컨벤션 작성
> [#152] README 코드 컨벤션 작성

- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/main/resources/logback-dev.xml
- src/main/resources/logback-test.xml
로그백 설정
dev -> logging level = Debug
test -> logging level = Info
ERROR 로그는 파일로 별도 저장
> [#140] Logback 설정

- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/main/resources/logback-dev.xml
- src/main/resources/logback-test.xml
Logback 파일 및 yml 설정 변경
logging.config 설정 추가됨
> [#161] Logback 파일 설정 변경

- README.md
- README 개발환경 이미지 변경
- README 개발환경 이미지 변경
> [#163] README 개발환경 이미지 변경

- .gitignore
- src/docs/asciidoc/ticket.adoc
docs 수정 및 로그파일 깃 제외
theater-find-all -> ticket-find-all 수정
logs 파일 gitignore 추가
> [#169] docs 수정

- README.md
- README ERD를 Table 설계도로 변경
- README ERD를 Table 설계도로 변경
> [#171] README ERD를 Table 설계도로 변경

- README.md
- README 개발환경 이미지 Redis 추가하기
- README 개발환경 이미지 Redis 추가하기
> [#184] README 개발환경 이미지 Redis 추가하기

- src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
- /users/refresh 통합 테스트 수정
-  /users/refresh 통합 테스트 수정
> [#192] /users/refresh 통합 테스트 수정

- src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/Account.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/Ticket.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/dto/RequestReservation.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/AccountRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/AccountService.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/PayService.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationService.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservedSeatService.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/TicketService.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/service/SeatService.java
- src/main/java/prgrms/marco/be02marbox/domain/user/service/UserService.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/AccountServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/ServiceTestUtil.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/TicketServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryTest.java
- 결제 기능 개발
- 결제 기능 개발
- ReservationService에 reservation 메소드 개발
- reservation 메소드에서 AccountService, TicketService, ReservedSeatService를 이용해 결제 후 티켓 생성
> [#196] 결제 기능 개발

- build.gradle
- src/main/java/prgrms/marco/be02marbox/config/QueryDslConfig.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryCustom.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryCustomImpl.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/TicketService.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryCustom.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryCustomImpl.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepository.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryCustom.java
- src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryCustomImpl.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/repository/MovieRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/movie/service/MovieServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/AccountServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/reservation/service/TicketServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenServiceTest.java
- src/test/java/prgrms/marco/be02marbox/domain/user/service/UserServiceTest.java
동적쿼리 QueryDSL 적용
SeatRepository
ScheduleRepository
ReservedSeatRepository 
에 있는 동적 쿼리를 QueryDSL로 변환
티켓의 경우 DTO 프로젝션은 또 다른 방법이어서 추후 학습 후 반영하겠습니다.
> [#195] QueryDSL 적용

- src/docs/asciidoc/reservation.adoc
- src/main/java/prgrms/marco/be02marbox/domain/exception/handler/ReservationExceptionHandler.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservationController.java
- src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationService.java
- src/main/resources/static/docs/openapi3.yaml
- src/test/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservationControllerTest.java
- 예약 기능 추가
- ResrvationController 추가
- PAY_AMOUNT -> TICKET_PRICE 로 변경 (티켓 가격이라는 의미가 더 잘 나타날거 같아서 변경)
- ReservationService 메소드에 주석 추가
- POST /reservation
<h3 id="_결제" style="box-sizing: border-box; margin: 1em 0px 0.5em; padding: 0px; font-family: &quot;Open Sans&quot;, &quot;DejaVu Sans&quot;, sans-serif; font-weight: 300; font-style: normal; color: rgb(204, 204, 204); text-rendering: optimizelegibility; line-height: 1.2; font-size: 1.375em; word-spacing: -0.05em; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; -webkit-text-stroke-width: 0px; background-color: rgb(69, 73, 74); text-decoration-thickness: initial; text-decoration-style: initial; …
> [#202] 예약 기능 컨트롤러 추가

- README.md
- mvp3 리드미 정리
- QueryDsl, S3, Jacoco, 결제 도메인 추가
> [#208] mvp3 리드미 정리

- src/main/resources/application.yml
- s3 default 설정 profile없어도 동작하도록 추가
> [#205] s3 default 설정정보 추가

- src/main/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleController.java
- src/test/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleControllerTest.java
- if 문 분기로 scheduleService 메서드 호출
- params를 이용해 메소드 분리
> [#140] Schedule 도메인 피드백 반영
